### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fzerorubigd** [seraheazari/MahsaAminiHashflag#13]
I want to use the image in other context, and it will be great if you set a license that let us use it freely (or if you get the image from somewhere else, to share the origin)

**Comment by seraheazari** [comment]
It was an image I found on my Twitter feed (there was no link to the artist in the tweet), TBH (and now I deeply regret it) I was too emotional to look up for the source or the artist (not sure if it was those kind of art that artist published anonymously or not), if anyone knows or found the artist please let me know, I'll ask them and if they're not happy, I'll change the hashflag icon. 

Regarding licence, I can't licence the Hashflag, because it's not my art, but for the code I'm open to suggestions.

This is the image I saved back then and used as the Hashflag.

![IMG_2476](https://user-images.githubusercontent.com/114618612/194713349-51c92469-b480-4979-bc84-0ff0f06f359e.JPG)

**Comment by fzerorubigd** [comment]
For the license, it depends on how you want to limit people on redistribute
this.
Mit has the least restrictions, but since this is not a library, I can
recommend GPL3 so if someone fork this, they should publish it again in the
future with the same license.
Also a customized Creative Commons can be good.
